[package]
name = "diverta2019_d"
version = "0.1.0"
authors = ["dekokun <dekokun@hatena.ne.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
