[package]
name = "agc038_a"
version = "0.1.0"
authors = ["dekokun <dekokun@hatena.ne.jp>"]
edition = "2018"
default-run = "agc038_a"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.1"
